apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api-server
  labels:
    app: public-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-api-server
  template:
    metadata:
      labels:
        app: public-api-server
    spec:
      containers:
        - name: public-api-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: public-api-server
spec:
  type: ClusterIP
  selector:
    app: public-api-server
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
